/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ANZYM
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    public JButton getBtn_Login_Admin() {
        return btn_Login_Admin;
    }

    public JButton getBtn_Login_Mhs() {
        return btn_Login_Mhs;
    }

    public JButton getBtn_keluar_mhs() {
        return btn_keluar_mhs;
    }

    public JButton getBtn_Keluar_Admin() {
        return btn_Keluar_Admin;
    }

    public JPasswordField getjLogin_Mhs_id_input() {
        return jLogin_Mhs_id_input;
    }

    public JTextField getjLogin_Mhs_user_input() {
        return jLogin_Mhs_user_input;
    }

    public JPasswordField getjLogin_Admin_id_input() {
        return jLogin_Admin_id_input;
    }

    public JTextField getjLogin_Admin_user_input() {
        return jLogin_Admin_user_input;
    }

    public void addListener (ActionListener A) {
        btn_Login_Admin.addActionListener(A);
        btn_Login_Mhs.addActionListener(A);
        btn_Keluar_Admin.addActionListener(A);
        btn_keluar_mhs.addActionListener(A);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        JWelcom = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTab_Mhs = new javax.swing.JTabbedPane();
        jPanel_Login_Mhs = new javax.swing.JPanel();
        jLogin_Mhs_user_label = new javax.swing.JLabel();
        jLogin_Mhs_user_input = new javax.swing.JTextField();
        jLogin_Mhs_id_label = new javax.swing.JLabel();
        btn_Login_Mhs = new javax.swing.JButton();
        btn_keluar_mhs = new javax.swing.JButton();
        jLogin_Mhs_id_input = new javax.swing.JPasswordField();
        jPanel_Login_Admin = new javax.swing.JPanel();
        jLogin_Mhs_user_label2 = new javax.swing.JLabel();
        jLogin_Mhs_user_input2 = new javax.swing.JTextField();
        jLogin_Mhs_id_label2 = new javax.swing.JLabel();
        jLogin_Mhs_btn2 = new javax.swing.JButton();
        jKeluar_Mhs_btn2 = new javax.swing.JButton();
        jLogin_Mhs_id_input2 = new javax.swing.JPasswordField();
        jPanel_Login_Dosen = new javax.swing.JPanel();
        jLogin_Mhs_user_label3 = new javax.swing.JLabel();
        jLogin_Admin_user_input = new javax.swing.JTextField();
        jLogin_Mhs_id_label3 = new javax.swing.JLabel();
        btn_Login_Admin = new javax.swing.JButton();
        btn_Keluar_Admin = new javax.swing.JButton();
        jLogin_Admin_id_input = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setAutoscrolls(true);

        JWelcom.setBackground(new java.awt.Color(204, 204, 204));
        JWelcom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JWelcom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JWelcom.setText("SELAMAT DATANG DI APLIKASI REGISTRASI MATA KULIAH");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Silahkan Login untuk masuk.");

        jTab_Mhs.setToolTipText("");

        jLogin_Mhs_user_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLogin_Mhs_user_label.setText("Username  :");

        jLogin_Mhs_user_input.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLogin_Mhs_user_input.setPreferredSize(new java.awt.Dimension(6, 26));
        jLogin_Mhs_user_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogin_Mhs_user_inputActionPerformed(evt);
            }
        });

        jLogin_Mhs_id_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLogin_Mhs_id_label.setText("Password   :");

        btn_Login_Mhs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Login_Mhs.setText("Login");
        btn_Login_Mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Login_MhsActionPerformed(evt);
            }
        });

        btn_keluar_mhs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_keluar_mhs.setText("Keluar");
        btn_keluar_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluar_mhsActionPerformed(evt);
            }
        });

        jLogin_Mhs_id_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogin_Mhs_id_inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Login_MhsLayout = new javax.swing.GroupLayout(jPanel_Login_Mhs);
        jPanel_Login_Mhs.setLayout(jPanel_Login_MhsLayout);
        jPanel_Login_MhsLayout.setHorizontalGroup(
            jPanel_Login_MhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Login_MhsLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel_Login_MhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLogin_Mhs_user_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLogin_Mhs_id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Login_MhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_Login_MhsLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btn_Login_Mhs)
                        .addGap(18, 18, 18)
                        .addComponent(btn_keluar_mhs))
                    .addComponent(jLogin_Mhs_user_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLogin_Mhs_id_input, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel_Login_MhsLayout.setVerticalGroup(
            jPanel_Login_MhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Login_MhsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel_Login_MhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogin_Mhs_user_label)
                    .addComponent(jLogin_Mhs_user_input, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel_Login_MhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogin_Mhs_id_label)
                    .addComponent(jLogin_Mhs_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Login_MhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Login_Mhs)
                    .addComponent(btn_keluar_mhs))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTab_Mhs.addTab("MAHASISWA", jPanel_Login_Mhs);

        jLogin_Mhs_user_label2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLogin_Mhs_user_label2.setText("Username  :");

        jLogin_Mhs_user_input2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLogin_Mhs_user_input2.setPreferredSize(new java.awt.Dimension(6, 26));
        jLogin_Mhs_user_input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogin_Mhs_user_input2ActionPerformed(evt);
            }
        });

        jLogin_Mhs_id_label2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLogin_Mhs_id_label2.setText("Password   :");

        jLogin_Mhs_btn2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLogin_Mhs_btn2.setText("Login");
        jLogin_Mhs_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogin_Mhs_btn2ActionPerformed(evt);
            }
        });

        jKeluar_Mhs_btn2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jKeluar_Mhs_btn2.setText("Keluar");
        jKeluar_Mhs_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKeluar_Mhs_btn2ActionPerformed(evt);
            }
        });

        jLogin_Mhs_id_input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogin_Mhs_id_input2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Login_AdminLayout = new javax.swing.GroupLayout(jPanel_Login_Admin);
        jPanel_Login_Admin.setLayout(jPanel_Login_AdminLayout);
        jPanel_Login_AdminLayout.setHorizontalGroup(
            jPanel_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Login_AdminLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLogin_Mhs_user_label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLogin_Mhs_id_label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_Login_AdminLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLogin_Mhs_btn2)
                        .addGap(18, 18, 18)
                        .addComponent(jKeluar_Mhs_btn2))
                    .addComponent(jLogin_Mhs_user_input2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLogin_Mhs_id_input2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel_Login_AdminLayout.setVerticalGroup(
            jPanel_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Login_AdminLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogin_Mhs_user_label2)
                    .addComponent(jLogin_Mhs_user_input2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogin_Mhs_id_label2)
                    .addComponent(jLogin_Mhs_id_input2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogin_Mhs_btn2)
                    .addComponent(jKeluar_Mhs_btn2))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTab_Mhs.addTab("DOSEN", jPanel_Login_Admin);

        jLogin_Mhs_user_label3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLogin_Mhs_user_label3.setText("Username  :");

        jLogin_Admin_user_input.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLogin_Admin_user_input.setPreferredSize(new java.awt.Dimension(6, 26));
        jLogin_Admin_user_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogin_Admin_user_inputActionPerformed(evt);
            }
        });

        jLogin_Mhs_id_label3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLogin_Mhs_id_label3.setText("Password   :");

        btn_Login_Admin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Login_Admin.setText("Login");
        btn_Login_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Login_AdminActionPerformed(evt);
            }
        });

        btn_Keluar_Admin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Keluar_Admin.setText("Keluar");
        btn_Keluar_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Keluar_AdminActionPerformed(evt);
            }
        });

        jLogin_Admin_id_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogin_Admin_id_inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Login_DosenLayout = new javax.swing.GroupLayout(jPanel_Login_Dosen);
        jPanel_Login_Dosen.setLayout(jPanel_Login_DosenLayout);
        jPanel_Login_DosenLayout.setHorizontalGroup(
            jPanel_Login_DosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Login_DosenLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel_Login_DosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLogin_Mhs_user_label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLogin_Mhs_id_label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Login_DosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_Login_DosenLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btn_Login_Admin)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Keluar_Admin))
                    .addComponent(jLogin_Admin_user_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLogin_Admin_id_input, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel_Login_DosenLayout.setVerticalGroup(
            jPanel_Login_DosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Login_DosenLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel_Login_DosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogin_Mhs_user_label3)
                    .addComponent(jLogin_Admin_user_input, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel_Login_DosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogin_Mhs_id_label3)
                    .addComponent(jLogin_Admin_id_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Login_DosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Login_Admin)
                    .addComponent(btn_Keluar_Admin))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTab_Mhs.addTab("ADMIN", jPanel_Login_Dosen);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JWelcom, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTab_Mhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JWelcom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTab_Mhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLogin_Mhs_user_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogin_Mhs_user_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogin_Mhs_user_inputActionPerformed

    private void btn_Login_MhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Login_MhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Login_MhsActionPerformed

    private void btn_keluar_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluar_mhsActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_keluar_mhsActionPerformed

    private void jLogin_Mhs_id_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogin_Mhs_id_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogin_Mhs_id_inputActionPerformed

    private void jLogin_Mhs_user_input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogin_Mhs_user_input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogin_Mhs_user_input2ActionPerformed

    private void jLogin_Mhs_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogin_Mhs_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogin_Mhs_btn2ActionPerformed

    private void jKeluar_Mhs_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKeluar_Mhs_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKeluar_Mhs_btn2ActionPerformed

    private void jLogin_Mhs_id_input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogin_Mhs_id_input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogin_Mhs_id_input2ActionPerformed

    private void jLogin_Admin_user_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogin_Admin_user_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogin_Admin_user_inputActionPerformed

    private void btn_Login_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Login_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Login_AdminActionPerformed

    private void btn_Keluar_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Keluar_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Keluar_AdminActionPerformed

    private void jLogin_Admin_id_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogin_Admin_id_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogin_Admin_id_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JWelcom;
    private javax.swing.JButton btn_Keluar_Admin;
    private javax.swing.JButton btn_Login_Admin;
    private javax.swing.JButton btn_Login_Mhs;
    private javax.swing.JButton btn_keluar_mhs;
    private javax.swing.JButton jKeluar_Mhs_btn2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jLogin_Admin_id_input;
    private javax.swing.JTextField jLogin_Admin_user_input;
    private javax.swing.JButton jLogin_Mhs_btn2;
    private javax.swing.JPasswordField jLogin_Mhs_id_input;
    private javax.swing.JPasswordField jLogin_Mhs_id_input2;
    private javax.swing.JLabel jLogin_Mhs_id_label;
    private javax.swing.JLabel jLogin_Mhs_id_label2;
    private javax.swing.JLabel jLogin_Mhs_id_label3;
    private javax.swing.JTextField jLogin_Mhs_user_input;
    private javax.swing.JTextField jLogin_Mhs_user_input2;
    private javax.swing.JLabel jLogin_Mhs_user_label;
    private javax.swing.JLabel jLogin_Mhs_user_label2;
    private javax.swing.JLabel jLogin_Mhs_user_label3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Login_Admin;
    private javax.swing.JPanel jPanel_Login_Dosen;
    private javax.swing.JPanel jPanel_Login_Mhs;
    private javax.swing.JTabbedPane jTab_Mhs;
    // End of variables declaration//GEN-END:variables
}
